/**
 * @version 1.4.2
 * Config.js - General configuration and structural thresholds for Lingo
 */

module.exports = {
    HeuristicName: "new",
    OP_SHIFT_THRESHOLD: 0x40,
    V4_HLEN: 92,
    V4_MOVIE_PROPS: {
        0x00: 'floatPrecision',
        0x01: 'mouseDownScript',
        0x02: 'mouseUpScript',
        0x03: 'keyDownScript',
        0x04: 'keyUpScript',
        0x05: 'timeoutScript',
        0x06: 'short time',
        0x07: 'abbr time',
        0x08: 'long time',
        0x09: 'short date',
        0x0a: 'abbr date',
        0x0b: 'long date'
    },
    V4_SPRITE_PROPS: {
        0x00: 'type',
        0x01: 'spriteNum',
        0x02: 'foreColor',
        0x03: 'backColor',
        0x04: 'startFrame',
        0x05: 'endFrame',
        0x06: 'member',
        0x07: 'visible',
        0x08: 'ink',
        0x09: 'blend',
        0x0a: 'script',
        0x0b: 'scriptNum',
        0x0f: 'loc',
        0x10: 'scoreColor',
        0x15: 'rect',
        0x16: 'width',
        0x17: 'height'
    },
    V4_ANIMATION_PROPS: {
        0x01: 'beepOn',
        0x02: 'buttonStyle',
        0x03: 'centerStage',
        0x04: 'checkBoxAccess',
        0x05: 'checkboxType',
        0x06: 'colorDepth',
        0x07: 'colorQD',
        0x08: 'exitLock',
        0x09: 'fixStageSize',
        0x0a: 'fullColorPermit',
        0x0b: 'imageDirect',
        0x0c: 'doubleClick',
        0x0d: 'key',
        0x0e: 'lastClick',
        0x0f: 'lastEvent',
        0x10: 'keyCode',
        0x11: 'lastKey',
        0x12: 'lastRoll',
        0x13: 'timeoutLapsed',
        0x14: 'multiSound',
        0x15: 'pauseState',
        0x16: 'quickTimePresent',
        0x17: 'selEnd',
        0x18: 'selStart',
        0x19: 'soundEnabled',
        0x1a: 'soundLevel',
        0x1b: 'stageColor',
        0x1d: 'switchColorDepth',
        0x1e: 'timeoutKeyDown',
        0x1f: 'timeoutLength',
        0x20: 'timeoutMouse',
        0x21: 'timeoutPlay',
        0x22: 'timer',
        0x23: 'preLoadRAM',
        0x24: 'videoForWindowsPresent',
        0x25: 'netPresent',
        0x26: 'safePlayer',
        0x27: 'soundKeepDevice',
        0x28: 'soundMixMedia'
    },
    V4_ANIMATION2_PROPS: {
        0x01: 'perFrameHook',
        0x02: 'number of castMembers',
        0x03: 'number of menus',
        0x04: 'number of castLibs',
        0x05: 'number of xtras'
    },
    V4_MEMBER_PROPS: {
        0x01: 'name',
        0x02: 'text',
        0x03: 'textStyle',
        0x04: 'textFont',
        0x05: 'textHeight',
        0x06: 'textAlign',
        0x07: 'textSize',
        0x08: 'picture',
        0x09: 'hilite',
        0x0a: 'number',
        0x0b: 'size',
        0x0c: 'loop',
        0x0d: 'duration',
        0x0e: 'controller',
        0x0f: 'directToStage',
        0x10: 'sound',
        0x11: 'foreColor',
        0x12: 'backColor',
        0x13: 'type'
    },
    SCRIPT_TYPE: {
        SCORE: 1,
        PARENT: 3,
        CAST: 4,
        LEGACY_PARENT: 6,
        LEGACY_BEHAVIOR: 7,
        LEGACY_CAST: 8
    },
    LITERAL_TYPE: {
        STRING: 1,
        INT: 2,
        FLOAT: 3,
        SYMBOL: 4,
        LIST: 5,
        FLOAT_V4: 9
    },
    COMMANDS_WITHOUT_PARENS: ['put', 'alert', 'set', 'go', 'try', 'catch', 'delete', 'hilite'],
    Labels: {
        ProtectedScript: "[Protected Script]"
    },
    OP_SPEC: {
        PUSHVAR: 0x01,
        MOVIEPROP: 0x1f,
        GETTOPLEVELPROP: 0x32
    }
};
